#!/usr/bin/env bash

# TODO download jimu plugins
PWD = `pwd`
ECLIPSE_HOME="`find ${PWD} -name 'eclipse*' -type d | head -1`"
PLUGIN_FILE="jimux_plugins.tar.gz"
echo "ECLIPSE_HOME=${ECLIPSE_HOME}"
rm -fr `find ${ECLIPSE_HOME}/plugins -name '*jimu*'`
rm -fr `find ${ECLIPSE_HOME}/plugins -name 'eclippers*'`
tar -zxvf ${PLUGIN_FILE} -C "${ECLIPSE_HOME}/plugins"
