#!/usr/bin/env bash

# TODO download jimu plugins
PWD = `pwd`
ECLIPSE_HOME="`find ${PWD} -name 'eclipse*' -type d | head -1`"
PLUGIN_FILE="jimux-plugins.zip"
echo "ECLIPSE_HOME=${ECLIPSE_HOME}"
unzip ${PLUGIN_FILE} -d "${ECLIPSE_HOME}/plugins"
