#!/usr/bin/env bash

# required packages
sudo apt-get install -y unzip openjdk-7-jdk ruby1.9.1 xvfb build-essential

PWD=`pwd`
# get eclipse
curl -o eclipse.tar.gz http://cloud.github.com/downloads/jimulabs/jimux_scripts/eclipse-java-3.7.2-linux-ADT20.tar.gz
tar -zxvf eclipse.tar.gz
ECLIPSE_HOME="`find ${PWD} -name eclipse* -type d`"

# android sdk
curl -o android-sdk.tgz http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz 
tar -zxvf android-sdk.tgz
ANDROID_SDK_HOME="`find ${PWD} -name android-sdk* -type d`"

# workspace
WORKSPACE="jimux-workspace"
SETTINGS_DIR="${WORKSPACE}/.metadata/.plugins/org.eclipse.core.runtime/.settings"
mkdir -p ${SETTINGS_DIR}

ADT_PREFS_PATH="${SETTINGS_DIR}/com.android.ide.eclipse.adt.prefs"
echo "Writing ADT prefs: ${ADT_PREFS_PATH}..."
cat > ${ADT_PREFS_PATH} <<EOF
com.android.ide.eclipse.adt.fixLegacyEditors=1
com.android.ide.eclipse.adt.sdk=${ANDROID_SDK_HOME}
eclipse.preferences.version=1
EOF

# eclim
curl -o eclim.jar http://cloud.github.com/downloads/jimulabs/jimux_scripts/eclim_1.7.11.jar

# install eclim into eclipse
echo "Installing eclim... ECLIPSE_HOME=${ECLIPSE_HOME}"
java \
  -Dvim.files=$HOME/.vim \
  -Declipse.home=${ECLIPSE_HOME} \
  -jar eclim.jar install


