#!/usr/bin/env bash

# required packages
sudo apt-get install -y unzip openjdk-7-jdk xvfb build-essential ant

PWD="`pwd`"
# get eclipse
curl -o eclipse.tar.gz http://cloud.github.com/downloads/jimulabs/jimux_scripts/eclipse-java-3.7.2-linux-ADT20.tar.gz
tar -zxvf eclipse.tar.gz
ECLIPSE_HOME="`find ${PWD} -name 'eclipse*' -type d | head -1`"

# android sdk
curl -o android-sdk.tgz http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz 
tar -zxvf android-sdk.tgz
curl -O -L https://github.com/jimulabs/jimux_scripts/raw/master/update_android_sdk.rb
chmod +x update_android_sdk.rb
ANDROID_SDK_HOME="`find ${PWD} -name 'android-sdk*' -type d`"
./update_android_sdk.rb --sdk-home "$ANDROID_SDK_HOME" \
  --filter platform-tool,android-8-17,google-api-8-17,"Google AdMob Ads SDK",\
"Google Analytics SDK","Google Cloud Messaging for Android Library",\
"Google Play services","Google Play Billing Library",\
"Google Play Licensing Library"

# archive_home
ARCHIVE_HOME="$HOME/jimux_archives"
mkdir -p $ARCHIVE_HOME

echo "Setting environment vars..."
cat >> $HOME/.bashrc <<EOF
export ANDROID_SDK_HOME=$ANDROID_SDK_HOME
export ECLIPSE_HOME=$ECLIPSE_HOME
export DEFAULT_WORKSPACE=$WORKSPACE
export JIMUX_ARCHIVE_HOME=$ARCHIVE_HOME
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386
EOF

echo "Please run this to load environment vars: \". ~/.bashrc\""

# # eclim
# curl -o eclim.jar http://cloud.github.com/downloads/jimulabs/jimux_scripts/eclim_1.7.11.jar
# 
# # install eclim into eclipse
# echo "Installing eclim... ECLIPSE_HOME=${ECLIPSE_HOME}"
# java \
#   -Dvim.files=$HOME/.vim \
#   -Declipse.home=${ECLIPSE_HOME} \
#   -jar eclim.jar install


